name: Build and Publish Docker Image

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract current version
        id: version
        run: |
          VERSIONS_JSON=$(curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/users/matiasmartin00/packages/container/pi-monitor/versions")

          LAST_VERSION=$(echo "$VERSIONS_JSON" | jq -r '[.[].metadata.container.tags[]] | map(select(test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))) | sort | last')

          if [[ "$LAST_VERSION" == "null" || -z "$LAST_VERSION" ]]; then
            NEW_VERSION="0.1.0"
          else
            MAJOR=$(echo "$LAST_VERSION" | cut -d. -f1)
            MINOR=$(echo "$LAST_VERSION" | cut -d. -f2)
            PATCH=$(echo "$LAST_VERSION" | cut -d. -f3)

            NEW_VERSION="$MAJOR.$((MINOR+1)).0"
          fi

          echo "Last version published: $LAST_VERSION"
          echo "New version: $NEW_VERSION"

          echo "version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/matiasmartin00/pi-monitor:${{ env.version }} .
          docker push ghcr.io/matiasmartin00/pi-monitor:${{ env.version }}

      - name: Tag latest
        run: |
          docker tag ghcr.io/matiasmartin00/pi-monitor:${{ env.version }} ghcr.io/matiasmartin00/pi-monitor:latest
          docker push ghcr.io/matiasmartin00/pi-monitor:latest
